feat: split semantic release step

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,6 +10,13 @@ on:
       - '**.md'
       - '.**'
 
+concurrency:
+  group: 'release'
+  cancel-in-progress: false
+
+permissions:
+  contents: write
+
 jobs:
   release:
     name: Release
@@ -27,14 +34,21 @@ jobs:
       - name: Release
         id: release
         # from https://github.com/cycjimmy/semantic-release-action/commits/main
-        uses: cycjimmy/semantic-release-action@bdd914ff2423e2792c73475f11e8da603182f32d
+        uses: cycjimmy/semantic-release-action@0a51e81a6baff2acad3ee88f4121c589c73d0f0e # v4.2.0
         with:
           semantic_version: 18.0.0
+          dry_run: true
           extra_plugins: |
             @semantic-release/release-notes-generator@10.0.3
             @semantic-release/git@10.0.1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      
+      - name: Fail if no new release was published
+        if: steps.release.outputs.new_release_published == 'false'
+        run: |
+          echo "No new release was published. Failing the workflow."
+          exit 1
 
       - name: Log in to the Container registry
         id: docker_login
@@ -77,3 +91,22 @@ jobs:
           labels: |
             maintainer=https://pagopa.it
             org.opencontainers.image.source=https://github.com/${{ github.repository }}
+
+      - name: Create Git Tag
+        if: steps.release.outputs.new_release_published == 'true'
+        run: |
+          git tag v${{ steps.release.outputs.new_release_version }}
+          git push origin v${{ steps.release.outputs.new_release_version }}
+      
+      - name: Create GitHub Release
+        if: steps.release.outputs.new_release_published == 'true'
+        uses: softprops/action-gh-release@v2.2.2
+        with:
+          tag_name: v${{ steps.release.outputs.new_release_version }}
+          name: Release v${{ steps.release.outputs.new_release_version }}
+          generate_release_notes: true
+          make_latest: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        
+          
